apis:
  main:
    root: ./openapi/openapi.yaml
extends:
  - recommended
rules:
  security-defined: off
  no-unused-components: warn
  no-ambiguous-paths: off
security: []
theme:
  openapi:
    htmlTemplate: ./docs/index.html
    showConsole: true
